/* eslint-disable func-names */
import DOM from './modules/DOM'

import './styles/main.scss'
import './assets/more.png'
import './assets/editPen.png'
import './assets/priority.png'
import './assets/trash.png'
import './assets/lazyPanda.png'
import './assets/novice.png'
import './assets/student.png'
import './assets/apprentice.png'
import './assets/bandit.png'
import './assets/warrior.png'
import './assets/boss.png'
import './assets/inbox.svg'
import './assets/today.svg'
import './assets/thisWeek.svg'
import './assets/completed.svg'
import './assets/bamboo.svg'
import './assets/trash.svg'
import './assets/editPen.svg'
import './assets/edit.svg'

DOM.loadContent()
